### ISSUE TITLE
Wrong `justify-content` in paginate and a couple general comments

### ISSUE THREAD

**Issue by XhmikosR** [DataTables/DataTablesSrc#125]
Hi, there.

```css
div.dataTables_wrapper div.dataTables_paginate ul.pagination {
    margin: 2px 0;
    white-space: nowrap;
    justify-content: flex-end; /* <-- this one */
}
```

The above is wrong, at least for small resolutions.

![paginate](https://user-images.githubusercontent.com/349621/41975127-83e8eaa4-7a22-11e8-93e1-e6e2071a3b88.jpg)

Ideally the paginate should be wrapped in a `nav` with proper `aria-label`s.

A couple of general comments:

* you are overqualifying your selectors; there's no need to do `div.dataTables_wrapper div.dataTables_paginate ul.pagination` for example. But I guess changing this would require a lot of changes because it's something done across the whole code base
* Bootstrap supports responsive tables out of the box (https://getbootstrap.com/docs/4.1/content/tables/#responsive-tables); With v1.10.16 I could just wrap the `table` in a `.table-responsive` `div` as per our docs. But with v1.10.18, the table shows the horizontal overflow and I have to do this:

```css
table.dataTable {
    max-width: 100% !important;
}
```

Would be nice if this was restored to what it was in v1.10.16.
