### ISSUE TITLE
Datatables 1.11.x CSS now includes images from www.datatables.net

### ISSUE THREAD

**Issue by gustavi** [DataTables/DataTablesSrc#196]
Hello,

I downloaded the last version of datatables (1.11.3) and it now includes 2 images from www.datatables.net domain.

This is a problem for offline websites where there is no DNS resolution. This is also a privacy concern, I don't want to perform 2 `GET` requests each time I use a website with datatables. I guess it's just an oversight.

```css
td.dtcontrol {
  background: url("https://www.datatables.net/examples/resources/details_open.png") no-repeat center center;
  cursor: pointer;
}

tr.dt-hasChild td.dt-control {
  background: url("https://www.datatables.net/examples/resources/details_close.png") no-repeat center center;
}
```

I'm not sure this is the good repository, feel free to move this in the good one.

---

EDIT 2021-11-25 : typo
