### ISSUE TITLE
Foundation 6 Style Class for Processing Div

### ISSUE THREAD

**Issue by tinnvec** [DataTables/DataTablesSrc#82]
When using the option `processing: true` in addition to the foundation style sheet, the class `panel` is applied to the processing div.

In Foundation 5, `.panel` was available and relatively similar to the Bootstrap component of the same name. In Foundation 6, that has become `.callout`.

If using the scss version of Foundation, there's a relatively simple workaround:
```SCSS
.panel {
    @include callout($white);
    z-index: 10; // Appears behind table without specifying z-index
}
```
